version: "3.9"
services:
  ansible_controller:
    build:
      context: ./hello-world/ansible_controller
      dockerfile: Dockerfile
    container_name: ansible_controller
    volumes:
      - type: bind
        source: ./hello-world/ansible_files
        target: /home/ansible_controller/ansible_files
  node_app:
    build:
      context: ./hello-world
      dockerfile: Dockerfile
    container_name: node_app
    ports:
      - "3000:3000"