- name: My first playbook
  hosts: all
  become: yes
  vars_files:
    - "vars/additional_vars"
  tasks:
    - name: Ping check using ping module
      ping:
    
    - name: Create a file using the command module
      command: sudo touch /home/ansible_controller/hello.txt

    - name: Create file usding the file module
      file:
        name: /home/ansible_controller/hello.txt
        state: touch
    
    - name: Install apache2 using apt module
      apt:
        name: apache2
        update_cache: yes
        state: present
    
    - name: Install packages using loop
      apt:
        name: "{{ item }}"
        update_cache: yes
        state: present
      loop:
        - jq
        - apache2
        - vim
    - name: Create a file using vars
      vars:
        filename: anotherhello
      command: sudo touch /home/ansible_controller/{{ filename }}.txt

    - name: Install packages using vars file
      apt:
        name: "{{ softwares }}"
        update_cache: yes
        state: present

# - name: Install apache2 only on ansible_target1 machine
#   hosts: ansible_target1
#   become: yes
#   tasks:
#     - name: install
#       apt:
#         name: apache2
#         update_cache: yes
#         state: present

# - name: Install apache2 only on ansible_target1 machine (using roles)
#   hosts: ansible_target1
#   become: yes
#   roles:
#     - apache2-install

# - name: Install apache2 only on target2 group of machines (using roles)
#   hosts: target2
#   become: yes
#   roles:
#     - apache2-install